#!/usr/bin/env bash
# Orchestrate the fair "latest-branch" benchmark across isolated Lake projects.
#
# Each tactic is benchmarked in its OWN Lake project pinned to its latest default
# branch and whatever Lean toolchain that branch currently declares (tracked live,
# not pinned). Results + a version manifest land under latest/results/.
#
# blaster's latest is v4.24.0 == the repo root project, so it is run there rather
# than duplicated (see --with-blaster).
#
# Requires bash 5 (associative-array-free, but nameref/${var^^} used); re-exec if old.
if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
    exec /opt/homebrew/bin/bash "$0" "$@"
fi
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/.." && pwd)"
BENCH="$REPO_ROOT/benchmarks/benchmark.sh"
BASH5="$(command -v /opt/homebrew/bin/bash || command -v bash)"
RESULTS="$HERE/results"
MANIFEST="$RESULTS/manifest.tsv"
TIMEOUT="${TIMEOUT:-20}"

mkdir -p "$RESULTS"

# tool table: dir | require-name | git-url | branch | tactic | build-module | import-override
#   dir             filesystem dir + results subdir (lowercase)
#   require-name    Lean package name in the lakefile AND lake-manifest (case matters:
#                   LeanHammer's package is "Hammer"; Lean-blaster's main renamed
#                   its package Solver -> Blaster)
#   build-module    the exact module the benchmark imports, so we build precisely
#                   what `lake env lean` will need
#   import-override (optional) tactic import to use instead of benchmark_config.sh's
#                   default — needed when the latest branch renamed its module
#                   namespace (blaster: Solver.Command.Tactic -> Blaster.Command.Tactic)
# (toolchain is fetched live from the branch, implementing "track moving branch")
TOOLS=(
    "blaster|Blaster|https://github.com/input-output-hk/Lean-blaster|main|blaster|Blaster.Command.Tactic|Blaster.Command.Tactic"
    "smt|smt|https://github.com/ufmg-smite/lean-smt.git|main|smt +model|Smt"
    "hammer|Hammer|https://github.com/JOSHCLUNE/LeanHammer.git|main|hammer|Hammer"
    "auto|auto|https://github.com/leanprover-community/lean-auto.git|main|auto|Auto.Tactic"
    "aesop|aesop|https://github.com/leanprover-community/aesop|master|aesop|Aesop"
)

# Package name must be a valid Lean identifier
pkg_name() { echo "${1^}Latest"; }

# Build the raw.githubusercontent URL for a repo's lean-toolchain on a branch
raw_toolchain_url() {
    local url="$1" branch="$2"
    url="${url%.git}"
    url="${url/github.com/raw.githubusercontent.com}"
    echo "$url/$branch/lean-toolchain"
}

scaffold() {
    local dir="$1" reqname="$2" url="$3" branch="$4" tactic="$5" import_override="${6:-}"
    local proj="$HERE/projects/$dir"
    mkdir -p "$proj"

    # 1. toolchain: fetch live from the tool's branch
    local tc
    tc="$(curl -fsSL "$(raw_toolchain_url "$url" "$branch")" 2>/dev/null | tr -d '[:space:]')"
    if [[ -z "$tc" ]]; then
        echo "  ! could not fetch toolchain for $dir from $branch" >&2
        return 1
    fi
    printf '%s\n' "$tc" > "$proj/lean-toolchain"

    # 2. lakefile: require the tool@branch + mathlib matching this toolchain
    cat > "$proj/lakefile.lean" <<EOF
import Lake
open Lake DSL

package $(pkg_name "$dir") where

-- Tactic under test: latest default branch (tracked live)
require ${reqname} from git "${url}" @ "${branch}"

-- Mathlib pinned to the tag matching this project's toolchain (STG4 imports Mathlib)
def leanVersion : String := s!"v{Lean.versionString}"
require "leanprover-community" / mathlib @ git leanVersion
EOF

    # 3. shared benchmark sources
    ln -sfn ../../../BlasterBenchmarks "$proj/BlasterBenchmarks"

    # 4. per-tool benchmark config (single tactic, central results dir)
    cat > "$proj/config.sh" <<EOF
#!/usr/bin/env bash
# Generated by run_latest.sh - per-tool benchmark override.
TACTICS=("${tactic}")
OUTPUT_DIR="${RESULTS}/${dir}"
TEMP_DIR="benchmark_temp"
EOF
    # Override the tactic's import when the latest branch renamed its module
    # namespace (TACTIC_IMPORTS is a -A array declared in benchmark_config.sh).
    if [[ -n "$import_override" ]]; then
        printf 'TACTIC_IMPORTS["%s"]="%s"\n' "$tactic" "$import_override" >> "$proj/config.sh"
    fi
    return 0
}

# manifest header (create once; per-tool rows are replaced in place so a single
# tool can be re-run without discarding the others)
[[ -f "$MANIFEST" ]] || printf 'tool\ttoolchain\tbranch\tresolved_commit\ttactic\tbuild_status\n' > "$MANIFEST"

# Append a manifest row, replacing any existing row for the same tool first.
# Uses awk (portable) rather than `grep -P`, which BSD/macOS grep lacks.
manifest_put() {
    local tool="$1"; shift
    local tmp="$MANIFEST.tmp"
    awk -F'\t' -v t="$tool" 'NR==1 || $1!=t' "$MANIFEST" > "$tmp" && mv "$tmp" "$MANIFEST"
    printf '%s\t%s\t%s\t%s\t%s\t%s\n' "$tool" "$@" >> "$MANIFEST"
}

run_tool() {
    local row="$1"
    IFS='|' read -r dir reqname url branch tactic module import_override <<< "$row"
    local proj="$HERE/projects/$dir"
    echo "==================== $dir ($branch) ===================="

    scaffold "$dir" "$reqname" "$url" "$branch" "$tactic" "$import_override" || {
        manifest_put "$dir" "?" "$branch" "?" "$tactic" "SCAFFOLD_FAIL"
        return
    }
    local tc; tc="$(tr -d '[:space:]' < "$proj/lean-toolchain")"
    echo "  toolchain: $tc"

    ( cd "$proj" || exit 1
      echo "  lake update...";              lake update           > update.log 2>&1
      echo "  cache get...";                lake exe cache get     > cache.log  2>&1 || true
      echo "  build ${module}...";          lake build "${module}" > build.log  2>&1
    )
    local build_rc=$?

    # resolved commit of the tool from the manifest
    local commit
    commit="$(python3 -c "import json,sys
try:
    d=json.load(open('$proj/lake-manifest.json'))
    for p in d['packages']:
        if p.get('name')=='$reqname': print(p['rev'][:9]); break
except Exception: print('?')" 2>/dev/null)"
    commit="${commit:-?}"

    if [[ $build_rc -ne 0 ]]; then
        echo "  BUILD FAILED (see $proj/build.log)"
        manifest_put "$dir" "$tc" "$branch" "$commit" "$tactic" "BUILD_FAIL"
        return
    fi

    echo "  running benchmark..."
    ( cd "$proj" && QUIET=1 "$BASH5" "$BENCH" run -c ./config.sh -t "$TIMEOUT" > bench.log 2>&1 )
    manifest_put "$dir" "$tc" "$branch" "$commit" "$tactic" "OK"
    echo "  done: results in $RESULTS/$dir"
}

# --- arg handling: which tools to run (default: all) ---
WANT=()
for a in "$@"; do
    case "$a" in
        all) for r in "${TOOLS[@]}"; do WANT+=("$r"); done ;;
        *) for r in "${TOOLS[@]}"; do [[ "$r" == "$a|"* ]] && WANT+=("$r"); done ;;
    esac
done
[[ ${#WANT[@]} -eq 0 ]] && { for r in "${TOOLS[@]}"; do WANT+=("$r"); done; }

for row in "${WANT[@]}"; do run_tool "$row"; done

echo; echo "===== MANIFEST ====="; column -t -s$'\t' "$MANIFEST"
